apiVersion: v1
kind: Service
metadata:
  name: aspnetcore
  labels:
     run: aspnetcore 
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    run: aspnetcore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcore
spec:
  selector:
    matchLabels:
      run: aspnetcore
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: aspnetcore
    spec:
      containers:
        - name: aspnetcore
          image: docker.io/vijayasankarv/collagelibrarymanagerbooksapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80