apiVersion: v1
kind: Service
metadata:
  name: aspnetcoreui
  labels:
    app: aspnetcoreui
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    run: aspnetcoreui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetcoreui
spec:
  selector:
    matchLabels:
      run: aspnetcoreui
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: aspnetcoreui
    spec:
      containers:
        - name: aspnetcoreui
          image: docker.io/vijayasankarv/collagelibraryui:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80